# Generated by Django 2.1.3 on 2018-11-28 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_ID', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('tournament_name', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('conditions', models.CharField(blank=True, max_length=30)),
                ('opposing_game_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opposition_game_id', to='db_output.Games')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_ID', models.AutoField(primary_key=True, serialize=False)),
                ('proper_name', models.CharField(max_length=30)),
                ('hometown', models.CharField(blank=True, max_length=30)),
                ('position', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('point_ID', models.AutoField(primary_key=True, serialize=False)),
                ('point_elapsed_seconds', models.IntegerField()),
                ('startingfence', models.CharField(max_length=30)),
                ('ourscore_EOP', models.IntegerField()),
                ('theirscore_EOP', models.IntegerField()),
                ('halfatend', models.BooleanField(default=False)),
                ('game_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_output.Games')),
            ],
        ),
        migrations.CreateModel(
            name='PossessionEvents',
            fields=[
                ('event_ID', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=30)),
                ('elapsedtime', models.IntegerField()),
                ('defender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='defender', to='db_output.Player')),
                ('passer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='passer', to='db_output.Player')),
                ('players', models.ManyToManyField(related_name='players_onfield', to='db_output.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Possessions',
            fields=[
                ('possession_ID', models.AutoField(primary_key=True, serialize=False)),
                ('point_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_output.Points')),
            ],
        ),
        migrations.CreateModel(
            name='Pulls',
            fields=[
                ('pull_ID', models.AutoField(primary_key=True, serialize=False)),
                ('hangtime', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('player_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_output.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_ID', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=30)),
                ('origin', models.CharField(blank=True, max_length=30)),
                ('division', models.CharField(blank=True, max_length=30)),
                ('players', models.ManyToManyField(to='db_output.Player')),
            ],
        ),
        migrations.AddField(
            model_name='possessionevents',
            name='possession_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_output.Possessions'),
        ),
        migrations.AddField(
            model_name='possessionevents',
            name='receiver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='db_output.Player'),
        ),
        migrations.AddField(
            model_name='points',
            name='pull_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_output.Pulls'),
        ),
        migrations.AddField(
            model_name='games',
            name='opposing_team_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opposition_id', to='db_output.Teams'),
        ),
        migrations.AddField(
            model_name='games',
            name='team_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_output.Teams'),
        ),
    ]
