# Generated by Django 2.1.3 on 2018-11-28 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='Players',
        ),
    ]
