# Generated by Django 2.1.3 on 2018-12-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0003_csvdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvdocument',
            old_name='document',
            new_name='file',
        ),
        migrations.AddField(
            model_name='csvdocument',
            name='your_team_name',
            field=models.CharField(default='Thunder2018', max_length=30),
            preserve_default=False,
        ),
    ]
