# Generated by Django 2.1.3 on 2018-12-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0004_auto_20181201_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='nickname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
