# Generated by Django 2.1.3 on 2018-12-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0008_auto_20181220_1827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pulls',
            new_name='Pull',
        ),
    ]
