# Generated by Django 2.1.3 on 2019-01-08 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0013_player_csv_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='file_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='db_output.csvDocument'),
        ),
    ]
