# Generated by Django 2.1.3 on 2019-01-08 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0014_game_file_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='file_model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='db_output.csvDocument'),
            preserve_default=False,
        ),
    ]
