# Generated by Django 2.1.3 on 2019-01-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0015_auto_20190108_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='possession_ID',
            new_name='possession',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='opposing_game_ID',
            new_name='opposing_game',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='opposing_team_ID',
            new_name='opposing_team',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='game_ID',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='pull_ID',
            new_name='pull',
        ),
        migrations.RenameField(
            model_name='possession',
            old_name='point_ID',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='pull',
            old_name='player_ID',
            new_name='player',
        ),
    ]
