# Generated by Django 2.1.3 on 2019-01-21 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0016_auto_20190121_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='team_ID',
            new_name='team',
        ),
        migrations.AlterField(
            model_name='game',
            name='opposing_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opposition_game', to='db_output.Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='opposing_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opposition', to='db_output.Team'),
        ),
    ]
