# Generated by Django 2.1.3 on 2019-01-21 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0017_auto_20190121_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='defender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defender', to='db_output.Player'),
        ),
        migrations.AlterField(
            model_name='event',
            name='passer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passer', to='db_output.Player'),
        ),
        migrations.AlterField(
            model_name='event',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='db_output.Player'),
        ),
    ]
