# Generated by Django 2.1.3 on 2019-01-22 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0018_auto_20190121_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='pull',
        ),
        migrations.AddField(
            model_name='csvdocument',
            name='parsed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pull',
            name='point',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='db_output.Point'),
            preserve_default=False,
        ),
    ]
