# Generated by Django 2.1.3 on 2019-01-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0019_auto_20190122_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdocument',
            name='parsed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
