# Generated by Django 2.1.3 on 2019-02-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0023_auto_20190126_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdocument',
            name='parsed',
            field=models.BooleanField(null=True),
        ),
    ]
