# Generated by Django 2.1.3 on 2019-02-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0024_auto_20190202_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='action',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
