# Generated by Django 2.1.3 on 2019-02-20 21:20

from django.db import migrations


def move_players_onfield(apps, schema_editor):
    # can't directly import models, might be newer
    Point = apps.get_model('db_output', 'Point')
    Possession = apps.get_model('db_output', 'Possession')
    Event = apps.get_model('db_output', 'Event')

    for point in Point.objects.all():
        first_possession = Possession.objects.filter(point=point).first()
        first_event = Event.objects.filter(possession=first_possession).first()
        for player in first_event.players.all():
            if player not in point.players.all():
                point.players.add(player)
            else:
                print(str(player) + 'already in point, doubly in first event?')
        point.save()


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0026_point_players'),
    ]

    operations = [
        migrations.RunPython(move_players_onfield)
    ]
