# Generated by Django 2.1.3 on 2019-02-20 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0027_auto_20190220_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='players',
        ),
    ]
