# Generated by Django 2.1.3 on 2019-02-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0028_remove_event_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('W', 'Womens'), ('M', 'Mens / Opens'), ('X', 'Mixed')], max_length=30),
        ),
    ]
