# Generated by Django 2.1.3 on 2019-02-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0029_auto_20190226_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='division',
            new_name='gender_division',
        ),
        migrations.AddField(
            model_name='team',
            name='age_division',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
