# Generated by Django 2.1.3 on 2019-03-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0030_auto_20190226_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='dob',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
