# Generated by Django 2.1.3 on 2019-04-09 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0031_auto_20190319_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pull',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='db_output.Player'),
        ),
    ]
