# Generated by Django 2.1.3 on 2019-04-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0033_auto_20190412_1534'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='team',
            managers=[
            ],
        ),
    ]
