# Generated by Django 2.1.3 on 2019-04-17 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_output', '0034_auto_20190412_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='possession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='db_output.Possession'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='db_output.Team'),
        ),
        migrations.AlterField(
            model_name='point',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='db_output.Game'),
        ),
        migrations.AlterField(
            model_name='possession',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possessions', to='db_output.Point'),
        ),
    ]
